In [11]:
matrix=[[1,2,3],[4,5,6],[7,8,9],[10,1,2]]
import numpy as np
matrix=np.array(matrix)
s=np.amax(matrix)
B=matrix/s
print(s)
print(B)

10
[[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]
 [1.  0.1 0.2]]
