In [2]:
import numpy as np
a = np.arange(120).reshape((10,3,4))
print(a)
b = np.arange(120)[::-1].reshape((3,4,10))
print(b)
np.dot(a, b)[0,0,0,0]


[[[  0   1   2   3]
  [  4   5   6   7]
  [  8   9  10  11]]

 [[ 12  13  14  15]
  [ 16  17  18  19]
  [ 20  21  22  23]]

 [[ 24  25  26  27]
  [ 28  29  30  31]
  [ 32  33  34  35]]

 [[ 36  37  38  39]
  [ 40  41  42  43]
  [ 44  45  46  47]]

 [[ 48  49  50  51]
  [ 52  53  54  55]
  [ 56  57  58  59]]

 [[ 60  61  62  63]
  [ 64  65  66  67]
  [ 68  69  70  71]]

 [[ 72  73  74  75]
  [ 76  77  78  79]
  [ 80  81  82  83]]

 [[ 84  85  86  87]
  [ 88  89  90  91]
  [ 92  93  94  95]]

 [[ 96  97  98  99]
  [100 101 102 103]
  [104 105 106 107]]

 [[108 109 110 111]
  [112 113 114 115]
  [116 117 118 119]]]
[[[119 118 117 116 115 114 113 112 111 110]
  [109 108 107 106 105 104 103 102 101 100]
  [ 99  98  97  96  95  94  93  92  91  90]
  [ 89  88  87  86  85  84  83  82  81  80]]

 [[ 79  78  77  76  75  74  73  72  71  70]
  [ 69  68  67  66  65  64  63  62  61  60]
  [ 59  58  57  56  55  54  53  52  51  50]
  [ 49  48  47  46  45  44  43  42  41  40]]

 [[ 39  38  37  36  35  

574

In [11]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [16]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

# Using fancy indexing
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
